version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    links:
      - nonrel_database
    environment:
      - MONGO_DATABASE=mongodb
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=nonrel_database
    depends_on:
      - nonrel_database
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    container_name: mongodb
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    logging:
      driver: none
