version: '3.8'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    links:
      - mongodb
    environment:
      - MONGO_DATABASE=mongodb
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
      # - postgres
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    container_name: mongodb
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    logging:
      driver: none
  # postgres:
  #     image: 'postgres:14.2'
  #     restart: always
  #     volumes:
  #       - './postgres_data:/var/lib/postgresql/data'
  #     environment:
  #       - POSTGRES_PASSWORD=123123
  #     ports:
  #     - '5432:5432'
